doc_center/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
 ]

doc_center/doc_center/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from core.views import logout_user
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("library/", include("library.urls")),
    path("services/", include("services.urls")),
    path('logout/', logout_user, name="logout"),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

doc_center/library/urls.py
from django.urls import path, re_path

from . import views

app_name = "library"

urlpatterns =[
    path("", views.index, name="index"),
    # create a document
    path("new-document", views.newDocument, name="new-document"),
    # issue a document
    re_path(r'^issue-document/(?P<pk>\d+)', views.issueDocument, name="issue-document"),
    # mark document as returned
    re_path(r'^return-book/(?P<pk>\d+)', views.returnDocument, name="return-book"),
    # document by id
    re_path(r'^document/(?P<pk>\d+)', views.singleDocument, name="document"),
     # documents by category
    path("search", views.documentsByCategory, name="search-documents"),
    # update document
    re_path(r'^update/(?P<pk>\d+)', views.updateDocument, name="update-document"),
    # delete document
    re_path(r'^delete/(?P<pk>\d+)', views.deleteDocument, name="delete-document")
]

doc_center/services/urls.py
from django.urls import path

from . import views

app_name ="services"

urlpatterns = [
    path("", views.index, name="index"),
    path("new-request", views.newRequest, name="new-request")
]

doc_center/core/models.py
from django.db import models

# Create your models here.

doc_center/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

INPUT_CLASS = "w-full rounded-lg mb-3 mt-3"


class LoginForm(AuthenticationForm):
    model = User
    fields = {"username", "password"}
    username = forms.CharField(widget= forms.TextInput(attrs={'placeholder': 'Enter your username', 'class': 'rounded-lg w-full mb-3 p-2'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password', 'class': 'rounded-xl w-full mb-3 p-2'}))

    # widgets = {
    #         "username": forms.TextInput(attrs={"class": INPUT_CLASS}),
    #         "password": forms.Select(attrs={'class': INPUT_CLASS}),
    #     }

doc_center/core/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from library.models import Book
from services.models import Service

# Create your views here.

# logged in user dashboard
@login_required
def index(request):
    documents = Book.objects.filter(issuing_officer = request.user, returned=False).all()
    services = Service.objects.filter(user = request.user).all()
    return render(request, "core/index.html", {"documents": documents, "services": services})


# logout user
def logout_user(request):
    logout(request)
    return redirect("library:index")

doc_center/core/templates/core/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <title>{% block title %}{% endblock %} || Document Center</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-200 font-serif leading-normal tracking-normal overflow-x-hidden">
        {% block scripts %}{% endblock %}
        <section class="flex gap-5">
            <aside class="bg-white shadow-xl w-64">
                <div class="sticky top-0">

                      <div class="p-4 border-b-2 border-b-gray-300">
                    <a href="/" class="font-semibold text-xl" >Docs Center</a>
                </div>

                <nav class="p-4 w-full">
                    <!-- navigation links -->
                    <ul class="">
                        <a href="/" class="text-sm font-medium text-black dark:text-white mb-4 active::text-red-500">
                           <li class="mb-2 bg-blue-500 p-2 rounded-md w-full cursor-pointer focus:bg-blue-900">Dashboard</li>
                        </a>
                        <a href="{% url 'services:index' %}" class="text-sm font-medium text-black dark:text-white mb-4">
                            <li class="mb-2 bg-blue-500 p-2 rounded-md w-full cursor-pointer focus:bg-blue-900">Services</li>
                        </a>
                        <a href="{% url 'services:new-request' %}" class="text-sm font-medium text-black dark:text-white mb-4">
                            <li class="mb-2 bg-blue-500 p-2 rounded-md w-full cursor-pointer focus:bg-blue-900">New Service</li>
                        </a>
                        <a href="{% url 'library:index' %}" class="text-sm font-medium text-black dark:text-white mb-4">
                            <li class="mb-2 bg-blue-500 p-2 rounded-md w-full cursor-pointer focus:bg-blue-900">Books</li>
                        </a>
                        <a href="{% url 'library:new-document' %}" class="text-sm font-medium text-black dark:text-white mb-4">
                            <li class="mb-2 bg-blue-500 p-2 rounded-md w-full cursor-pointer focus:bg-blue-900">Lend Book</li>
                        </a>
                    </ul>
                </nav>
               
                </div>
            </aside>

            <section class="container mx-auto">
                <!-- navigation -->
                <nav class="w-full flex justify-between items-center p-4 sticky top-0 container mx-auto border-b-2 border-b-gray-300 z-20 bg-gray-200">
                            <div>
                        <h3 class="text-lg font-medium uppercase">{% block crumbs %}{% endblock %}</h3>
                    </div>

                    <!-- navigation list -->
                    <ul class="flex items-center space-x-6">
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'admin:index' %}" class="text-sm font-semibold bg-blue-500 hover:bg-blue-700 text-white rounded-lg p-2">Admin Dashboard</a></li>  
                        <li><a href="{% url 'logout' %}" class="text-sm font-semibold bg-red-400 hover:bg-red-700 text-white rounded-lg p-2">Logout</a></li> 
                        {% else %}
                            <li><a href="{% url 'core:login' %}" class="text-sm font-semibold bg-blue-500 hover:bg-blue-700 text-white rounded-lg p-2">Login</a></li>
                            <li><a href="{% url 'admin:index' %}" class="text-sm font-semibold bg-blue-500 hover:bg-blue-700 text-white rounded-lg p-2">Admin</a></li>  
                        {% endif %}                  
                    </ul>
                    </nav>

                <!-- main body -->
                <section class="min-h-screen">
                    <!-- loader -->
                   <div class="h-screen flex justify-center items-center  z-10" id="loading_container" >
                      <!-- <div class="w-64 h-64 rounded-full bg-blue-600 border-solid " id="spinner" >Loading .....</div> -->
                      <h1>Loading.......</h1>
                    </div>

			        <section class="min-h-screen p-4">
                       {% block content %}{% endblock %}
			        </section>
		           </div>
                </section>

                <!-- footer -->
                <footer class="container mx-auto border-t border-t-gray-500 p-4 flex justify-between items-center">
                    <h3 class="text-sm font-medium">Lake Basin Development Authority</h3>
                    <small class="text-lg font-medium" id="copyright">Copyright  </small>
                </footer>

            </section>

        </section>

         <!-- javascript -->
    <script src="/static/js/app.js"></script>
		
	</body>
</html>

doc_center/core/templates/core/index.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Dashboard {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} Dashboard {% endblock %}

<!-- content for the body -->
{% block content %}
 
     <div>
        <h2 class="text-2xl">Hello <span>{{request.user}}</span>, Welcome to your dashboard </h2>
        <div class="flex items-center gap-4 mt-3">
            <div class="flex flex-col items-center justify-center bg-blue-500 p-3 rounded-md shadow-md">
                <h3 class="text-lg text-white font-semibold">{{documents.count}}</h3>
                <span class="font-medium text-white">books issued</span>
            </div>

            <div class="flex flex-col items-center justify-center bg-blue-500 p-3 rounded-md shadow-md">
                <h3 class="text-lg text-white font-semibold">{{services.count}}</h3>
                <span class="font-medium text-white">services handled</span>
            </div>
        </div>
     </div>


    <!-- borrowed books -->
     {% if documents %}
    <div class="mt-6">
        <!-- loop documents -->
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700 mt-4">
                <thead class="bg-blue-600 dark:bg-gray-800">
                    <tr>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Id</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Title</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Author</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Issued_to</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Date Borrowed</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Due Date</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Issued by</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Date Returned</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Returned</th>
                        <!-- <th scope="col" class="px-6 py-3.5 text-lg font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Document Actions</th> -->
                    </tr>
                </thead>

                <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700  shadow-md rounded-sm">
                    {% for document in documents %}
                      <tr>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.id }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ document.title }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ document.author }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.issued_to }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.date_borrowed }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.due_back }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ document.issuing_officer.username }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.date_returned }}</td>
                         <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap"> <a href="{% url 'library:return-book' document.id %}" class="text-blue-600 text-lg" >Receive Back</a> </td>
                      </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
    {% else %}
    <div class="mt-3 h-96 bg-white flex items-center justify-center">
        <h3 class="text-2xl font-semibold ">You have not issued any books</h3>
    </div>
    {% endif %}


    <!-- services -->
    <h3 class="my-5 font-semibold text-xl">Services handled by {{request.user}}</h3>


    {% if services %}
    <div class="">
        <!-- loop documents -->
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead class="bg-blue-600 dark:bg-gray-800">
                    <tr>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Service Type</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Date</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Title</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Department</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Customer's name</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Number of pages</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Quantity Rate</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Total</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Customers Signature</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Served by</th>
                    </tr>
                </thead>

                <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700  shadow-md rounded-sm">
                    {% for service in services %}
                      <tr>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ service.type.name }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ service.date_created }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ service.title_of_document }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ service.department }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ service.customers_name }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ service.no_of_pages }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ service.quantity_rate }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ service.total }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ service.customers_signature }}</td>
                         <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap"> {{service.user.username}} </td>
                      
                      </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
    {% else %}
    <div class="mt-3 h-96 bg-white flex items-center justify-center">
        <h3 class="text-2xl font-semibold ">No service requests have been handled by you</h3>
    </div>
    {% endif %}

{% endblock %}

doc_center/core/templates/core/login.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Login {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} Login {% endblock %}

<!-- content for the body -->
{% block content %}

<section class="h-96">

<div class="w-1/2 mx-auto mt-60">
    <form action="" method="post" class="w-full">

        {% csrf_token %}

        {{ form.as_p }}

        <div class="flex justify-end w-full">
                <button class="bg-blue-500 text-white w-full p-2 rounded-md ">Login</button>
        </div>
    </form>
</div>


{% endblock %}