doc_center/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
 ]

doc_center/doc_center/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from core.views import logout_user
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("library/", include("library.urls")),
    path("services/", include("services.urls")),
    path('logout/', logout_user, name="logout"),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

doc_center/library/urls.py
from django.urls import path, re_path

from . import views

app_name = "library"

urlpatterns =[
    path("", views.index, name="index"),
    # create a document
    path("new-document", views.newDocument, name="new-document"),
    # issue a document
    re_path(r'^issue-document/(?P<pk>\d+)', views.issueDocument, name="issue-document"),
    # mark document as returned
    re_path(r'^return-book/(?P<pk>\d+)', views.returnDocument, name="return-book"),
    # document by id
    re_path(r'^document/(?P<pk>\d+)', views.singleDocument, name="document"),
     # documents by category
    path("search", views.documentsByCategory, name="search-documents"),
    # update document
    re_path(r'^update/(?P<pk>\d+)', views.updateDocument, name="update-document"),
    # delete document
    re_path(r'^delete/(?P<pk>\d+)', views.deleteDocument, name="delete-document")
]

doc_center/library/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
#     
# documents
class Book(models.Model):
    author = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    no_of_volume = models.CharField(max_length=255, null=True)
    issued_to = models.CharField(max_length=255, null=True)
    borrower_signature = models.IntegerField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    returned = models.BooleanField(default=False)
    borrowed = models.BooleanField(default=False)
    issuing_officer = models.ForeignKey(User, related_name="books", on_delete=models.CASCADE, default=1)
    due_back = models.DateField(null=False)
    date_borrowed = models.DateField(null=False)
    date_returned = models.DateField(null = True)

    class Meta:
        ordering = ('title',)
        verbose_name_plural = "Books"

    def __str__(self) -> str:
        return self.title

doc_center/library/forms.py
from django import forms

from .models import Book

INPUT_CLASS = "w-full py-3 rounded-lg mb-3 mt-3"

class NewDocumentForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["author", "title", "no_of_volume", "date_borrowed", "due_back", "issued_to", "borrower_signature"]
        widgets = {
            "author": forms.TextInput(attrs={"class": INPUT_CLASS, "placeholder": "Author of the book"}),
            "title": forms.TextInput(attrs={"class": INPUT_CLASS, "placeholder": "Title of the book"}),
            "no_of_volume": forms.TextInput(attrs={"class": INPUT_CLASS, "placeholder": "Volume number"}),
            "date_borrowed": forms.DateInput(attrs={"class": INPUT_CLASS, "placeholder": "Title of the book", "type": "date"}),
            "due_back": forms.DateInput(attrs={"class": INPUT_CLASS, "placeholder": "Title of the book", "type": "date"}),
            "issued_to": forms.TextInput(attrs={"class": INPUT_CLASS, "placeholder": "Name of the borrower"}),
            "borrower_signature": forms.NumberInput(attrs={"class": INPUT_CLASS, "placeholder": "Borrower signature"}),
        }


# lend document to a user
class LendDocument(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ["name", "categories", "description", "image", "created_by", "returned", "borrowed", "return_date", "issued_by"]
        widgets = {
            "issued_to": forms.TextInput(attrs={"class": INPUT_CLASS}),
            "return_date": forms.DateInput(attrs={"class": INPUT_CLASS})
        }

# return document
class ReturnBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["returned", "issued_to", "date_returned", "borrower_signature" ]
        widgets = {
            "returned": forms.CheckboxInput(attrs={"class": "w-8 h-8", "type": "checkbox"}),
            "issued_to": forms.TextInput(attrs={"class": INPUT_CLASS}),
            "date_returned": forms.DateInput(attrs={"class": INPUT_CLASS, "type": "date"}),
            "borrower_signature": forms.NumberInput(attrs={"class": INPUT_CLASS})
        }

doc_center/library/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Book

from .forms import NewDocumentForm, LendDocument, ReturnBook

# Create your views here.

# index
def index(request):
    # find all documents
    documents = Book.objects.filter(returned = False).order_by("-id").all()
    return render(request, "library/index.html", {"documents": documents})

# search documents
def documentsByCategory(request):
    if request.method == "GET":
        query = request.GET.get("search")
        searchRequest = request.GET.get("search")
        if query is not None:
            lookup = Q(title__icontains = query) | Q(author__icontains = query) | Q(issued_to__icontains = query)
            documents = Book.objects.filter(lookup).distinct()
            return render(request, "library/index.html", {"query": query, "documents": documents, "searchRequest": searchRequest})
        else:
            return render(request, "library/index.html")  
    else:
        return render(request, "library/index.html")

# new document
@login_required
def newDocument(request):
    if request.method == "POST":
        form = NewDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document= form.save(commit=False)
            document.issuing_officer = request.user
            document.save()
            return redirect("library:index")
    else:
        form = NewDocumentForm()
    return render(request, "library/new-document.html", {"form": form})


# document by id
def singleDocument(request, pk):
    document = get_object_or_404(Book, pk=pk)
    return render(request, "library/document.html", {'document': document})

# update document
@login_required
def updateDocument(request, pk):
    document = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = NewDocumentForm(instance=document, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("library:index")
    else:
        form = NewDocumentForm(instance=document)
    return render(request, "library/edit-document.html", {"form": form, "object": document})


# delete document
@login_required
def deleteDocument(request, pk):
    document_object = get_object_or_404(Book, pk=pk)
    document_object.delete()
    return redirect(reverse("library:index"))

# issue book only when the column borrowed is false
@login_required
def issueDocument(request, pk):
    document = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = LendDocument(instance=document, data=request.POST)
        if form.is_valid():
            document = form.save(commit=False)
            document.issued_to = request.POST.get("issued_to")
            document.borrowed = True
            document.issued_by = request.user.username
            document.save()
            return redirect("library:index")
    else:
        form = LendDocument(instance=document)
    return render(request, "library/issue-document.html", {"form": form, "object": document})

# mark borrowed books as returned
@login_required
def returnDocument(request, pk):
    document = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = ReturnBook(instance=document, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("library:index")
    else:
        form = ReturnBook(instance=document)
    return render(request, "library/edit-document.html", {"form": form, "object": document})

doc_center/library/templates/library/category.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Category {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} {{category}} {% endblock %}

<!-- content for the body -->
{% block content %}
    
<div>
    documents by category
    <h3>found {{documents}}</h3>

    {% for document in documents.documents %}
      {{document.name}}
    {% endfor %}
</div>

{% endblock %}

doc_center/library/templates/library/delete.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Delete {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} Delete Document{% endblock %} 

<!-- content for the body -->
{% block content %}
    
<div>
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</div>

{% endblock %}

doc_center/library/templates/library/document.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Document Details {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} {{document.name}} {% endblock %}

<!-- content for the body -->
{% block content %}
    
<div>
    document details
</div>

{% endblock %}

doc_center/library/templates/library/edit-document.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Edit Document {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} Update {% endblock %}

<!-- content for the body -->
{% block content %}

<div>

   <div>
        <form action="" method="post">
            {% csrf_token %}
            
            {{ form.as_p }}

             {% if form.errors or form.non_field_errors %}
             <div class="p-4 bg-red-100 rounded-lg">
                {% for field in form %}
                   {{ field.errors }}
                {% endfor %}

                <!-- show form errors -->
                {{ form.non_field_errors }}
             </div>
            {% endif %}

            <div class="flex justify-end w-full">
                <button class="bg-blue-500 text-white p-3 rounded-md shadow-md">Receive Book</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

doc_center/library/templates/library/index.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Documents {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} Library {% endblock %}

<!-- content for the body -->
{% block content %}

<!-- search bar -->
<div class="w-full mb-4 flex items-center justify-center mx-auto">
    <form action="{% url 'library:search-documents' %}" value="{{request.GET.q}}" method="get" class="w-full mx-auto text-lg shadow-md border-transparent rounded-lg">
        <input type="text" placeholder="Search documents" value="{{request.GET.q}}" name="search" class="w-full rounded-lg p-4 text-xl" >
        <!-- <input type="submit" value="Search" name="submit"> -->
    </form>
</div>

<!-- filter returned books, all books, overdue books -->
<!-- <div class="flex justify-between items-center mb-3">
    <div class="flex items-center space-x-6">
        <form action="{% url 'library:search-documents' %}" method="get" value="{{category.name}}" class="bg-white rounded-lg p-2 shadow-md flex gap-2 cursor-pointer">
            <input type="submit" name="search" value="returned"/>
            <h3 class="text-blue-600">Returned books</h3>
        </form> 
    </div> 
</div> -->


<!-- <div class="mt-6"> -->
     {% if searchRequest %}
       {% if documents %}
            <h3>Results for {{query}}</h3>
        {% else %}
            <h3 class="text-2xl font-semibold">Did not find any documents for <span class="text-blue-600">{{query}}</span></h3>
       {% endif %}
     {% endif %}
  
    {% if documents %}
    <div class="">
        <!-- loop documents -->
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead class="bg-blue-600 dark:bg-gray-800">
                    <tr>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Id</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Title</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Author</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Issued_to</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Date Borrowed</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Due Date</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Issued by</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Date Returned</th>
                        <th scope="col" class="px-6 py-3.5 text-sm font-normal text-left rtl:text-right text-black dark:text-gray-400">Receive Back</th>
                        <!-- <th scope="col" class="px-6 py-3.5 text-lg font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Document Actions</th> -->
                    </tr>
                </thead>

                <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700  shadow-md rounded-sm">
                    {% for document in documents %}
                      <tr>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.id }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ document.title }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ document.author }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.issued_to }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.date_borrowed }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.due_back }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap capitalize">{{ document.issuing_officer.username }}</td>
                        <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap">{{ document.date_returned }}</td>
                         <td class="px-6 py-3.5 text-sm font-medium text-left rtl:text-right whitespace-nowrap"> 
                            <a href="{% url 'library:return-book' document.id %}" class="text-blue-600 text-lg" >Receive Back</a> 
                        </td>
                      </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
    {% else %}
    <div class="mt-3">
        <h3 class="text-2xl font-semibold ">No documents available</h3>
    </div>
    {% endif %}

{% endblock %}

doc_center/library/templates/library/issue-document.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Issue Document {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} Issue Document {% endblock %}

<!-- content for the body -->
{% block content %}

<section class="h-96">

<div class="flex gap-4">
    <form action="" method="post" class="w-1/2">

        {% csrf_token %}

       {{ form.as_p }}

        <div class="flex justify-end w-full">
                <button class="bg-blue-500 text-white w-full p-2 rounded-md ">Issue document</button>
        </div>
    </form>

    <!-- generate issue tracker -->
    <div class="w-1/2">
        generate issue tracker
    </div>
</div>


{% endblock %}

doc_center/library/templates/library/new-document.html
<!-- extend base template -->
{% extends 'core/base.html' %}

<!-- title -->
{% block title %} Lend {% endblock %}

<!-- bread crumbs -->
{% block crumbs %} Lend Book {% endblock %}

<!-- content for the body -->
{% block content %}

<div>

    <div>
        <form action="" method="post">
            {% csrf_token %}
            
            {{ form.as_p }}

             {% if form.errors or form.non_field_errors %}
             <div class="p-4 bg-red-100 rounded-lg">
                {% for field in form %}
                   {{ field.errors }}
                {% endfor %}

                <!-- show form errors -->
                {{ form.non_field_errors }}
             </div>
            {% endif %}

            <div class="flex justify-end w-full">
                <button class="bg-blue-500 text-white p-2 rounded-md">Add Document</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}